from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import (
    CustomPasswordResetView, CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView, CustomPasswordResetCompleteView, 
    dashboard, ledger_page_details, receipt_detail, upload_vouchers_from_excel,
    voucher_detail, day_book, ledger_page, trail_balance, download_excel,
    download_pdf, upload_vouchers_success, download_contra_excel,
    download_contra_pdf, upload_receipt_from_excel, upload_receipt_success,
    upload_progress, create_contra, list_contra, delete_contra
)

urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('create-receipt/', views.create_receipt, name='create_receipt'),
    path('receipt-success/<int:receipt_id>/', views.receipt_success, name='receipt_success'),
    path('list-receipts/', views.list_receipts, name='list_receipts'),
    path('delete-voucher/<int:voucher_id>/', views.delete_voucher, name='delete_voucher'),
    path('approve-voucher/<int:voucher_id>/', views.approve_voucher, name='approve_voucher'),
    path('reject-voucher/<int:voucher_id>/', views.reject_voucher, name='reject_voucher'),
    path('view-voucher/<int:voucher_id>/', views.view_voucher, name='view_voucher'),
    path('edit-vouchers/', views.edit_vouchers_list, name='edit_vouchers_list'),
    path('edit-voucher/<int:voucher_id>/', views.edit_voucher, name='edit_voucher'),
    path('create-voucher/', views.create_voucher, name='create_voucher'),
    path('voucher-success/<int:voucher_id>/', views.voucher_success, name='voucher_success'),
    path('convert-amount-to-words/', views.convert_amount_to_words, name='convert_amount_to_words'),
    path('upload-receipt-from-excel/', upload_receipt_from_excel, name='upload_receipt_from_excel'),
    path('list-vouchers/', views.list_vouchers, name='list_vouchers'),
    path('approver-page/', views.approver_page, name='approver_page'),
    path('day-book/', day_book, name='day_book'),
    path('day-book/<int:ledger_id>/', day_book, name='day_book_with_ledger_id'),
    path('receipt/<str:type_of_receipt>/', receipt_detail, name='receipt_detail'),
    path('voucher/<str:head_of_account>/', views.voucher_detail, name='voucher_detail'),

    path('voucher/<int:voucher_id>/', voucher_detail, name='view_voucher'), 
    path('ledger_page/', ledger_page, name='ledger_page'),
    path('ledger_page_details/', ledger_page_details, name='ledger_page_details'),
    path('trail_balance/', views.trail_balance, name='trail_balance'),
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', auth_views.PasswordResetView.as_view(), name='forgot_password'),
    path('reset-password/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('change-password/', auth_views.PasswordChangeView.as_view(), name='change_password'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('upload-vouchers-from-excel/', views.upload_vouchers_from_excel, name='upload_vouchers_from_excel'),
    path('dashboard/', dashboard, name='dashboard'),
    path('upload-vouchers-success/', upload_vouchers_success, name='upload_vouchers_success'),
    path('upload-progress/', upload_progress, name='upload_progress'),
    path('upload-receipt-success/', upload_receipt_success, name='upload_receipt_success'),
    path('create_contra/', create_contra, name='create_contra'),
    path('list_contra/', list_contra, name='list_contra'),
    path('delete_contra/<int:contra_no>/', delete_contra, name='delete_contra'),
    path('download-excel/', download_excel, name='download_excel'),
    path('download-pdf/', download_pdf, name='download_pdf'),
    path('download-contra-excel/', download_contra_excel, name='download_contra_excel'),
    path('download-contra-pdf/', download_contra_pdf, name='download_contra_pdf'),
]
