# accounts/utils.py
from num2words import num2words # type: ignore

def amount_to_words(amount):
    return num2words(amount)
def generate_auto_receipt_number():
    # Implement logic to auto-generate receipt number
    return "AutoGeneratedNumber"
from datetime import datetime, timedelta
from django.utils import timezone

def get_date_range(date_range):
    today = timezone.now().date()
    if date_range == 'today':
        return today, today
    elif date_range == 'yesterday':
        yesterday = today - timedelta(days=1)
        return yesterday, yesterday
    elif date_range == 'this_week':
        start_of_week = today - timedelta(days=today.weekday())
        return start_of_week, today
    elif date_range == 'last_week':
        start_of_last_week = today - timedelta(days=today.weekday() + 7)
        end_of_last_week = start_of_last_week + timedelta(days=6)
        return start_of_last_week, end_of_last_week
    elif date_range == 'this_month':
        start_of_month = today.replace(day=1)
        return start_of_month, today
    elif date_range == 'last_month':
        first_day_of_this_month = today.replace(day=1)
        last_day_of_last_month = first_day_of_this_month - timedelta(days=1)
        start_of_last_month = last_day_of_last_month.replace(day=1)
        return start_of_last_month, last_day_of_last_month
    else:
        return None, None

def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days) + 1):
        yield start_date + timedelta(n)
