# Generated by Django 5.0.6 on 2024-06-16 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_number',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('manual_book_no', 'manual_receipt_no')},
        ),
    ]
