# Generated by Django 5.0.6 on 2024-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_voucher_voucher_number_alter_receipt_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_number',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type_of_receipt',
            field=models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Type 3', 'Type 3')], max_length=50),
        ),
    ]
