# Generated by Django 5.0.6 on 2024-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_receipt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(default='2024-06-16', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('manual_book_no', 'manual_receipt_no')},
        ),
    ]
