# Generated by Django 5.0.6 on 2024-06-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_voucher_voucher_number_alter_receipt_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_number',
        ),
    ]
