# Generated by Django 5.0.6 on 2024-06-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_receipt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(auto_now_add=True, default='1111-11-11'),    
            preserve_default=False,
        ),
    ]
