# Generated by Django 5.0.6 on 2024-06-22 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_receipt_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='amount',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
