# Generated by Django 5.0.6 on 2024-06-22 07:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_receipt_manual_book_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.PositiveIntegerField(default='000', validators=[accounts.models.positive_integer_validator]),
            preserve_default=False,
        ),
    ]
