# Generated by Django 5.0.6 on 2024-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_receipt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
