# Generated by Django 5.0.6 on 2024-06-24 05:55

import accounts.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_receipt_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='1111-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='mode_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='paid_to',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='payment_purpose',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='purchased_by',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_no',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='phone',
            field=models.PositiveIntegerField(validators=[accounts.models.positive_integer_validator]),
        ),
        migrations.AddField(
            model_name='voucher',
            name='head_of_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.headofaccount'),
        ),
    ]
