# Generated by Django 5.0.6 on 2024-07-17 05:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_receipt_address_alter_receipt_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.PositiveIntegerField(validators=[accounts.models.positive_integer_validator]),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='manual_book_no',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[accounts.models.positive_integer_validator]),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[accounts.models.positive_integer_validator]),
        ),
    ]
