# Generated by Django 5.0.6 on 2024-07-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_receipt_amount_alter_receipt_manual_book_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type_of_receipt',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Type 2', 'Type 2'), ('Type 3', 'Type 3')], default='Donation', max_length=50),
        ),
    ]
