# Generated by Django 5.0.6 on 2024-07-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_receipt_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
