# Generated by Django 5.0.6 on 2024-07-20 05:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_receipt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[accounts.models.positive_integer_validator]),
        ),
    ]
