# Generated by Django 5.0.6 on 2024-07-20 07:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_receipt_amount_alter_receipt_manual_book_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='manual_book_no',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[accounts.models.positive_integer_validator]),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
