# Generated by Django 5.0.6 on 2024-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_receipt_manual_book_no_alter_receipt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='manual_book_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
