# Generated by Django 5.0.6 on 2024-07-20 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_receipt_amount_alter_receipt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
