# Generated by Django 5.0.6 on 2024-07-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_receipt_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='manual_receipt_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
