# Generated by Django 5.0.6 on 2024-07-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_receipt_cheque_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
