# Generated by Django 5.0.6 on 2024-07-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_voucher_amount_in_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='manual_receipt_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
