# Generated by Django 5.0.6 on 2024-07-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_receipt_manual_receipt_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='payment_purpose',
            new_name='on_account_of',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='purchased_by',
            new_name='received_by',
        ),
    ]
