# Generated by Django 5.0.7 on 2024-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='manual_receipt_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('manual_book_no', 'manual_receipt_no')},
        ),
    ]
