# Generated by Django 5.1 on 2024-09-19 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_receipt_manual_receipt_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='log_type',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='screen_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='work_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type_of_receipt',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Sadqa', 'Sadqa'), ('Zakat', 'Zakat'), ('Atiya', 'Atiya'), ('Fidiya', 'Fidiya'), ('Tasdeeq-Nama', 'Tasdeeq-Nama'), ('Isala-e-Sawab', 'Isala-e-Sawab')], default='Donation', max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
