# Generated by Django 5.0.7 on 2024-08-07 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_receipt_manual_receipt_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='screen_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='work_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
