# Generated by Django 5.1 on 2024-09-19 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_useractivitylog_log_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contra',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
