# Generated by Django 5.1 on 2024-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_contra_contra_no_alter_contra_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='total_receipts_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balance',
            name='total_receipts_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
