# Generated by Django 5.1 on 2024-09-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_voucher_financial_year_voucher_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('financial_year', 'sequence_number', 'mode_of_payment')},
        ),
    ]
