# Generated by Django 5.1 on 2024-10-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_receipt_type_of_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
