# Generated by Django 5.1 on 2024-10-29 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
