# Generated by Django 5.1 on 2024-11-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_balance_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
