# Generated by Django 5.1.3 on 2024-12-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_group_ledger_subgroup_receipt_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='subgroup',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='accounts.subgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='accounts.group'),
            preserve_default=False,
        ),
    ]
